apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: prod
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
