apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ./Deployment.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata
        value:
          namespace: prod
    target:
      kind: Application

  - patch: |-
      - op: replace
        path: /metadata
        value:
          namespace: prod
    target:
      kind: ApplicationSet
