apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
  - patch: |-
      - op: replace
        path: /spec/destination
        value:
          server: http://34.100.180.218:8080
          namespace: prod
    target:
      kind: Application

  - patch: |-
      - op: replace
        path:  /spec/template/spec/destination
        value:
          server: http://34.100.180.218:8080
          namespace: prod
    target:
      kind: ApplicationSet