apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: default
spec:
  destination:
    namespace: default
    cluster: https://34.93.114.1
  project: default
  source:
    path: app-set/prod/
    repoURL: https://github.com/climbablebug44/argo-assignment
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false