apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      # shubham cluster
      - cluster: dev
        url: https://kubernetes.default.svc
      # ashwin cluster
      - cluster: prod
        url: http://34.100.180.218:8080
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/climbablebug44/argo-assignment
        targetRevision: HEAD
        path: app-set/{{cluster}}
        # create two folders with cluster name prod and dev. this generator will use them

      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
