apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patches:
  - patch: |-
        path: /spec/destination
        value:
          server: https://kubernetes.default.svc
          namespace: dev
    target:
      kind: Application
