apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base/

patches:
  - patch: |-
      - op: replace
        path: /metadata
        value:
          namespace: dev
    target:
      kind: Application

  - patch: |-
      - op: replace
        path: /metadata
        value:
          namespace: dev
    target:
      kind: ApplicationSet
