apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base/

patches:
  - patch: |-
      - op: add
        path: /spec/destination
        value:
          serverURL: "https://kubernetes.default.svc"
          namespace: dev
    target:
      kind: Application
