apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app
  namespace: default
spec:
  destination:
    namespace: dev
    serverURL: https://kubernetes.default.svc
  project: default
  source:
    path: app-set/base/applications/mysql
    repoURL: https://github.com/climbablebug44/argo-assignment
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: default
spec:
  destination:
    namespace: dev
    serverURL: https://kubernetes.default.svc
  project: default
  source:
    path: app-set/base/applications/nginx
    repoURL: https://github.com/climbablebug44/argo-assignment
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: default
spec:
  destination:
    namespace: dev
    serverURL: https://kubernetes.default.svc
  project: default
  source:
    path: app-set/base/applications/redis
    repoURL: https://github.com/climbablebug44/argo-assignment
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
