apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
  namespace: default
spec:
  destination:
    namespace: bgdk
  project: default
  source:
    path: dev
    repoURL: https://gitlab.com/jasmine.harit/argocd-app-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false