apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-appset-local
  namespace: default

spec:
  generators:
  - list:
      elements:
      # - name: mysql
      - name: redis
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/climbablebug44/argo-assignment
        targetRevision: HEAD
        path: 'app-set/base/applications/{{name}}'
        # create two folders with cluster name prod and dev. this generator will use them
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
