apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./Application-nginx.yaml
- ./Application-mysql.yaml
- ./Application-redis.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/destination
        value:
          serverURL: https://kubernetes.default.svc
          namespace: dev
    target:
      kind: Application
